package:
  name: ngsutils
  version: '0.5.9'

source:
  url: https://github.com/ngsutils/ngsutils/archive/ngsutils-0.5.9.tar.gz
  md5: 6212d6de740c42aa2c6b5f6785465860

build:
  number: 0
  skip: True  # [py3k]

requirements:
  build:
    - python >=2.7.0
    - pysam
    - cython
    - samtools
    - eta
    - coverage
    - swalign
  run:
    - python >=2.7.0
    - pysam
    - cython
    - samtools
    - eta
    - coverage
    - swalign

test:
  commands:
    - python -m unittest discover ngsutils

about:
  home: http://ngsutils.org
  license: LICENSE
  summary: "Tools for next-generation sequencing analysis http://ngsutils.org"
