package:
  name: swalign
  version: "0.3.3"

source:
  fn: swalign-0.3.3.tar.gz
  url: https://pypi.python.org/packages/72/97/cb26a99ee2e1796b0ab28a955e3568607826a44999654f6880d4e00174ac/swalign-0.3.3.tar.gz
  md5: 64c55d09775d4875bc419a08a43dc6fa
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - swalign = swalign:main
    #
    # Would create an entry point called swalign that calls swalign.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1
  skip: True  # [py3k]

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - swalign

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/mbreese/swalign/
  license: UNKNOWN
  summary: 'Smith-Waterman local aligner'
  license_family: Other

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
